README.md
Remove the PayloadResponse message. Both client and server can send Data messages.
=> Rename PayloadDispatch to Data

cmd/connector_service/main.go, internal/config/config.go, internal/controller/api/api.spec.json, internal/controller/api/management.go, internal/controller/api/management_test.go, internal/controller/api/message_receiver.go, internal/controller/api/message_receiver_test.go, internal/controller/api/openapi_spec_handler_test.go, internal/controller/api/spec_handler.go, internal/controller/connection_manager_test.go, internal/controller/types.go, internal/mqtt/receptor_proxy.go
Add new metadata field to the rest interface
Make the api base url configurable
=> Add metadata to rest interface

internal/controller/api/message_receiver_test.go, internal/controller/connection_manager_test.go, internal/mqtt/connection_handler.go, internal/mqtt/receptor_proxy.go
Removing some duplication in the proxy
=> Implementing disconnect messages

cmd/connector_service/main.go, cmd/test_client/main.go, internal/config/config.go, internal/mqtt/client_options.go, internal/mqtt/connection_handler.go, internal/platform/utils/jwt_utils/jwt.go, internal/platform/utils/tls_utils/tls_utils.go
Moving tls configuration out of the mqtt code
Separating concerns
Cleanup
Refactoring
=> Refactoring the mqtt client configuration

cmd/connector_service/main.go, cmd/test_client/main.go, internal/config/config.go, internal/controller/connected_client_recorder.go, internal/mqtt/connection_handler.go, internal/mqtt/types.go
This is certainly not perfect but it looks like it works in my testing.
I still need to modify it to send the connected client id.  I need to touch base with the inventory team on how they want me to send that.
=> Inventory integration

internal/controller/account_resolver.go
URL was incorrect.
Removed unneeded debug statements
=> fix bop url

internal/controller/sources_recorder.go, internal/mqtt/connection_handler.go, internal/mqtt/dispatcher_handler_test.go
Experimenting with a test for the processDispatchers method
=> Minor cleanup in processDispatchers method

internal/controller/account_resolver.go, internal/controller/connected_client_recorder.go, internal/controller/sources_recorder.go, internal/domain/types.go, internal/mqtt/connection_handler.go
This is basically stubbed out at the moment.
I'll follow this up later with a real Identity object.
=> Pass the platform identity around to the different modules

internal/controller/api/api.spec.json
https://issues.redhat.com/browse/RHCLOUD-12784
=> update API spec for /message status code to match the implementation

cmd/connector_service/main.go, internal/config/config.go, internal/mqtt/connection_handler.go, internal/mqtt/receptor_proxy.go, internal/mqtt/receptor_proxy_factory.go, internal/mqtt/topic.go, internal/mqtt/topic_test.go
Make the topic prefix configurable
Move the topic building/verification into a single place
=> Make topic prefix configurable

internal/controller/account_resolver.go, internal/controller/connected_client_recorder.go, internal/platform/utils/identity_utils/identity.go, internal/platform/utils/identity_utils/identity_test.go
This approach is kind of experimental.
=> Add logic to set the owner_id in the inventory add_host message

internal/mqtt/receptor_proxy.go
Jamming a panic in the ping ...just to test out openshifts handling of this panic.  I hope openshift restart the pod and logs a restart
=> Testing...jamming a panic in the ping method

cmd/test_client/main.go, internal/config/config.go, internal/mqtt/receptor_proxy.go
https://issues.redhat.com/browse/RHCLOUD-13010
Signed-off-by: Stephen Adams <tsadams@gmail.com>
=> [fix] Remove sleep hacks

deploy/clowdapp.yml
I added rhc as plugin for testing. I am still unsure about this setting as rhc plugin has a few sets of tests and I only need to run a subset.
=> Add testing and rhc plugin spec

internal/middlewares/auth.go, internal/middlewares/auth_test.go
Added org_id to the auth middleware and created a test for a request with an org_id
=> Add org_id to auth middleware [RHCLOUD-17663] and GetOrgID() to Principal interface [RHCLOUD-17664]

db/migrations/000005_add_org_id_column.down.sql, db/migrations/000005_add_org_id_column.up.sql
Created a db migration to add the org_id column as a varchar.
=> Add migration to create org_id column [RHCLOUD-17661]

internal/controller/api/api.spec.json
define operationId for connection status operations
Client code generator is struggling due to how similar the operation paths are. Add operation id to make it easier to distinguish the two operations.
Define operation id in API spec.
Tested with client code generator manually
Feel free to adjust the operation ids as you like. I don't mind using other ids as long as they are unique.
=> define operationId for connection status operations

internal/controller/api/pagination.go
Fix pagination last link calculation.  Borrow Jozef's approach.
Change variable names to use camel case in pagination code.
=> Fix pagination last link calculation.  Borrow Jozef's approach.

deploy/clowdapp.yml
Add Playbook dispatcher PSK
To be able to run integration tests between Cloud Connector and Playbook Dispatcher in ephemeral envs.
Add a test playbook dispatcher PSK to the cloud-connector-psks secret
=> Add Playbook Dispatcher PSK for testing in Ephemeral envs

internal/connection_repository/permitted_tenant_connection_locator.go
Fixed the is not null check in the permitted tenant connection lookup logic.
=> Fix is not null check in sql

internal/connection_repository/permitted_tenant_connection_locator.go
Modify the way empty org_id matching guard is implemented
Modify the way empty org_id matching guard is implemented
Modify the sql connection lookup query
Tests already exist
=> Modify the way empty org_id matching guard is implemented

deploy/clowdapp.yml
Add Ingress as Optional Dependency to be deployed in ephemeral envs
Ingress is required by the contract tests
Add Ingress service as Optional Dependency
=> Add ingress as optional dependency required for contract testing

deploy/clowdapp.yml
Adjust path to tenant-utils image
=> Adjust path to tenant-utils image

deploy/clowdapp.yml
=> Set the prometheus gateway env var correctly

deploy/clowdapp.yml, deploy/run_org_id_populator.yaml
Try a new build of the org-id column populator
=> Try a new build of the org-id column populator

deploy/clowdapp.yml
=> Fix tenant-util image ref

deploy/clowdapp.yml, deploy/run_org_id_populator.yaml
Run org-id populator job via app-interface
=> Run org-id populator job via app-interface

deploy/clowdapp.yml
Adding the CJI to the deploy/clowdapp.yml file didn't seem to work, so i'm removing the cji from clowdapp
=> Remove cji from clowdapp

deploy/clowdapp.yml
Add config-manager psk for ephemeral envs
=> Add config-manager psk for ephemeral envs

internal/mqtt/utils.go
Fix an issue where the & was getting changes to \u0026 in the message content
This encoding of the message content is breaking satellite.
Use a json encoder and call SetEscapeHTML(false)
=> Fix an issue where the & was getting changes to \u0026 in the message content

cmd/cloud-connector/inventory_stale_timestamp_updater.go, cmd/cloud-connector/kafka_message_consumer.go, cmd/cloud-connector/mqtt_message_consumer.go, internal/config/config.go, internal/connection_repository/permitted_tenant_connection_locator_test.go, internal/connection_repository/sql_connection_registrar_test.go, internal/controller/connected_client_recorder.go, internal/platform/queue/consumer.go, internal/platform/queue/producer.go, internal/platform/queue/sasl.go, internal/platform/queue/types.go
=> Refactoring auth related changes to the kafka consumers and producers

cmd/cloud-connector/inventory_stale_timestamp_updater.go, cmd/cloud-connector/kafka_message_consumer.go, cmd/cloud-connector/mqtt_message_consumer.go, go.mod, go.sum, internal/config/config.go, internal/connection_repository/permitted_tenant_connection_locator_test.go, internal/connection_repository/sql_connection_registrar_test.go, internal/controller/connected_client_recorder.go, internal/platform/queue/consumer.go, internal/platform/queue/producer.go, internal/platform/queue/sasl.go, internal/platform/queue/types.go
Add the necessary libraries and configs to use SASL kafka auth and SSL
The managed kafka environment requires we support sasl auth and ssl. This makes that possible for cloud-connector
Add the kafka sasl info to the config via clowder. Also create a tls dialer for the kafka connection. 
Unable to test the SSL connection, but other tests seem to pass fine locally
I'm slightly skeptical regarding the ssl implementation here. The segmentio library doens't directly support the SSL cert, so you have to go through the crypto/tls package. I looked into segmentio to see if there are plans to support a ssl.cert param of some kind, but they currently have no interest in it. Hopefully the tls config works.
=> Add kafka auth

internal/connection_repository/permitted_tenant_connection_locator.go, internal/connection_repository/sql_connection_locator.go, internal/connection_repository/sql_connection_registrar.go
Explicitly set timeouts on the db queries
Not setting the timeout could cause a db query to hang
=> Explicitly set timeouts on the db queries

internal/platform/queue/sasl.go
There's a very small typo on the "scram" word which may cause an issue in the future.
N/A
N/A
No
N/A
=> fix: typo on the Kafka Sasl scram mechanism

internal/controller/api/api.spec.json
Design v2 of the REST interface [[RHCLOUD-18524]](https://issues.redhat.com/browse/RHCLOUD-18524)
- Split of "management" versions "end user" operations
- Replace references of account with org_id
- Replace references of node_id with client_id [[RHCLOUD-17021]](https://issues.redhat.com/browse/RHCLOUD-17021)
Part of the migration from EBS account numbers to org_id. Also removes outdated reference to node_id from receptor.
Added api.spec.v2.json with the required changes.
No new tests required
Any other notes about the PR that would be useful for the reviewer.
https://github.com/RedHatInsights/secure-coding-checklist
Secure Coding Checklist
=> Design v2 REST interface [RHCLOUD-18524] & [RHCLOUD-17021]

dev-full-stack.yml, dev.yml
Starts up the dependencies and cloud connector components.
[Based on a compose file by Link](https://github.com/RedHatInsights/config-manager/commit/918ed3fc8645fdf40e392077a477f4f5c5c32390)
[RHCLOUD-19166](https://issues.redhat.com/browse/RHCLOUD-19166)
Creates an easier development env.
=> Changed compose file to start the cloud connector parts

internal/controller/account_resolver.go
generates uuid, request id passed along as an http header
=> generate uuid and pass

db/migrations/000007_alter_account_and_org_id_null.down.sql, db/migrations/000007_alter_account_and_org_id_null.up.sql
Remove `NOT NULL` from the `account` field and add `NOT NULL` to the `org_id` field.
[RHCLOUD-18528](https://issues.redhat.com/browse/RHCLOUD-18528)
[RHCLOUD-18529](https://issues.redhat.com/browse/RHCLOUD-18529)
Part of EBS to OrgID migration
Added an additional migration step
No tests added
=> Orgid nonnull field

internal/middlewares/metrics_middleware.go
Modify the metrics middleware to record the http call duration [RHCLOUD-20686](https://issues.redhat.com/browse/RHCLOUD-20686)
We need to record the http call duration for the latency slo
Modify the metrics middleware to record the time the call takes
=> Modify the metrics middleware to record the http call duration

go.mod, go.sum
Update paho library [RHCLOUD-21194]
=> Update paho library [RHCLOUD-21194]

internal/platform/queue/sasl.go, internal/platform/utils/jwt_utils/jwt.go, internal/platform/utils/tls_utils/tls_utils.go
[RHCLOUD-21391](https://issues.redhat.com/browse/RHCLOUD-21391)
=> Run file paths through filepath.Clean()

internal/platform/queue/sasl.go, internal/platform/utils/tls_utils/tls_utils.go
Set the minimum tls version to 1.3 [RHCLOUD-21359]
=> Set the minimum tls version to 1.3 [RHCLOUD-21359]

internal/cloud_connector/message_handlers.go, internal/config/config.go, internal/mqtt/connector_client_proxy.go, internal/mqtt/utils.go
Add timeout value to the mqtt token.Wait() [RHCLOUD-21244]
=> Add timeout value to the mqtt token.Wait()

internal/controller/connected_client_recorder.go
Do not eat kafka writer errors that happen when sending inventory the add_host message
=> Do not eat kafka writer errors that happen when sending inventory the add_host message

deploy/clowdapp.yml
Set the inventory stale timestamp updater job's chunksize to 100
=> Set the inventory stale timestamp updater job's chunksize to 100

internal/controller/connected_client_recorder.go, internal/controller/connected_client_recorder_test.go
Register connection with inventory when convert2rhel worker is present
=> Register connection with inventory when convert2rhel worker is present

internal/controller/connected_client_recorder.go
=> Rename rhc bash worker name

cmd/cloud-connector/connection_count.go, cmd/cloud-connector/main.go, internal/config/config.go
https://issues.redhat.com/browse/RHCLOUD-20974
=> WIP Connection count

internal/controller/account_resolver.go, internal/controller/account_resolver_test.go
Unmarshaling response 
https://issues.redhat.com/browse/RHCLOUD-21190
Infrastructure are going to change the non- 200 response. We need to change the return error as an error instead of a string 
Created a new type that will send a json message 
- [X ] General Coding Practices
=> Unmarshaling response

internal/controller/account_resolver.go, internal/controller/account_resolver_test.go
=> Tweak the gateway error response stringer

dashboards/grafana-dashboard-insights-cloud-connector-general.configmap.yaml
=> Working on adding slos to dashboard

dashboards/grafana-dashboard-insights-cloud-connector-general.configmap.yaml
=> Update dashboard 2

go.mod, go.sum, internal/controller/account_resolver.go
Implementin Cache
[RHCLOUD-28630](https://issues.redhat.com/browse/RHCLOUD-28630)
using lru  cache from hashicorp 
- [X ] General Coding Practices
=> First cache try

internal/controller/account_resolver_test.go
Adding some tests of the account resolver response caching
=> Adding some tests of the account resolver response caching

.github/workflows/pr.yml, deploy/clowdapp.yml, go.mod, go.sum, internal/config/config.go, internal/controller/account_resolver.go, internal/controller/metrics.go
=> Account resolver cache tweaks

deploy/clowdapp.yml
Allow the account id mapping cache settings to be configurable during deployment
=> Allow the account id mapping cache settings to be configurable during deployment

internal/config/config.go
=> Remove kafka topic config workaround

internal/connection_repository/sql_connection_locator_v2.go
=> Do not eat/ignore the error

pr_check.sh
Switch to the new Ephemeral cluster 
To run the E2E tests there (instead on the temporary CRCD cluster)
switching the priority of the available clusters
N/A
N/A
=> Switch to ephemeral

.dockerignore, Dockerfile, build_deploy.sh
=> Be more restrictive while building the image

Dockerfile
=> Run microdnf update during docker build

deploy/clowdapp.yml
=> Make tls key/cert optional for mqtt connection

pr_check.sh
=> Fix component name in pr_check.sh

internal/cloud_connector/utils.go, internal/cloud_connector/utils_test.go
=> Handle empty canonical facts better

.tekton/cloud-connector-pull-request.yaml, .tekton/cloud-connector-push.yaml
=> Update build source image in tekton for release 

.tekton/cloud-connector-pull-request.yaml, .tekton/cloud-connector-push.yaml
=> CLoud COnnector testing release for konflux 

internal/controller/connected_client_recorder.go, internal/controller/connected_client_recorder_test.go, internal/domain/types.go, internal/platform/logger/types.go
https://issues.redhat.com/browse/RHCLOUD-35613
=> Use org id as kafka message key for inventory

internal/controller/connected_client_recorder.go
=> Use org id as kafka message key for inventory (set balancer=hash)

internal/controller/connected_client_recorder.go, internal/platform/queue/producer.go
=> Use org id as kafka message key for inventory 3

go.mod, go.sum
Updating golang packages to fix CVE's 
Fix Vulnerabilities
Upddate packages for .net and .crypto
- [x ] General Coding Practices
=> Upgrade golang packages
