RedHatInsights/cloud-connector

README.md
Permit a data message to include an optional set of key/value pairs as metadata.
=> Add "metadata" to data message

cmd/connector_service/main.go, cmd/test_client/main.go, internal/config/config.go, internal/mqtt/client_options.go, internal/mqtt/connection_handler.go
Persistent sessions will allow a newly started cloud-connector to
get notified of client connections and disconnections which happened
while the cloud-connector was down.
There appears to be a bit of a race condition in the paho client.
The paho client appears to receive messages from the broker
before the subscriber is completely "wired up".  Added a default
publish handler to work around that issue.
The issue and workaround are mentioned in the Common Problems section here:
https://pkg.go.dev/github.com/eclipse/paho.mqtt.golang
=> Implement persistent sessions

internal/controller/api/api.spec.json
Gathered what I could from the code. Looks like we just send an OK
status and empty JSON if the disconnect is successful. I don't see items
in the spec that account for the 400s, so I didn't put that in.
Let me know if there are additional needs or if I misread anything
RHCLOUD-12532
Signed-off-by: Stephen Adams <tsadams@gmail.com>
=> [api] Add disconnect endpoint to API spec

internal/mqtt/message_construction.go, internal/mqtt/receptor_proxy.go
This is going to kick over the service if it receives an error while trying to publish an mqtt message.  I'm spawning a new go routine and sleeping for 1 second before taking the poison pill.  Hopefully the 1 second sleep time gives the logs enough time to get sent to cloudwatch.
OpenShift will recognize that the service fell over and restart it automatically.
This is a temporary bandaid.
https://issues.redhat.com/browse/RHCLOUD-14297
=> Fall over if an error happens while attempting to publish a mqtt message

go.mod, internal/controller/api/message_receiver.go, internal/controller/api/message_receiver_test.go
Restricts the sending of empty strings with the `directive` field in the `/message` endpoint.
=> Don't allow empty strings for directive field (RHCLOUD-1231)

pr_check.sh
I added "cloud-connector" to IQE_FILTER_EXPRESSION so only the tests for cloud connector will be run. The iqe-rhc-plugin has tests for a few components and I need to just run the ones for cloud connector.
=> Add cloud connector to IQE_FILTER_EXPRESSION

cmd/test_client/main.go, db/migrations/000004_add_message_id_and_message_sent_column.down.sql, db/migrations/000004_add_message_id_and_message_sent_column.up.sql, internal/cloud_connector/message_handlers.go, internal/cloud_connector/message_handlers_test.go, internal/connection_repository/sql_connection_registrar.go, internal/connection_repository/types.go, internal/domain/types.go, internal/platform/db/connection.go
This is a phase 1 (crawl approach) to handling duplicate and out of order online messages.  With this approach, I am storing the _sent_ time and _message_id_ of the latest recorded online message.  With each online message received, the stored _message_id_ and _sent_ time are compared.  If the stored _message_id_ matches the incoming _message_id_, then the message is a duplicate and its discarded.  If the _sent_ time of the incoming message is before the stored _sent_ time, then the message is an old message and its discarded.
Right now, the message id and message sent timestamp is stored as field in the connection table.  The other option is to split this data out to a different table.  I'm not sure about the best approach.  Should the message metadata be stored in a different table? …
=> Phase 1 handle out of order online messages

internal/controller/api/management.go, internal/controller/api/management_test.go, internal/controller/api/message_receiver.go, internal/controller/api/message_receiver_test.go, internal/controller/api/pagination_test.go, internal/controller/api/test_utils.go, internal/middlewares/auth.go, internal/middlewares/auth_test.go, internal/middlewares/turnpike_auth.go, internal/middlewares/turnpike_auth_test.go
Modify the main authentication middleware to take a high-order function that handles the x-rh-identity based authentication.  This PR wraps the existing x-rh-identity authentication function with a function that enforces the Turnpike based authentication.
This approach allows for separation of concerns (the existing identity header authenticator only handles looking for the identity header, parsing the identity header) while providing flexibility to add new checks (Turnpike based authentication) to different endpoints.
=> Modifying the management endpoint to require turnpike based authentication

internal/mqtt/connector_client_proxy.go, internal/mqtt/connector_client_proxy_factory.go
Reuse an instance of the logger object across the proxy instead of created a new instance in each method
Rename the "this" variable
=> Minor cleanup of the proxy code

internal/controller/api/api.spec.json, internal/controller/api/management.go, internal/controller/api/management_test.go
Updated the reconnect endpoint to return an error if passed a negative or decimal delay parameter.
=> Positive, integer reconnect delay [RHCLOUD-13033] and [RHCLOUD-13030]

cmd/cloud-connector/inventory_stale_timestamp_updater.go, internal/connection_repository/sql_connection_locator.go, internal/connection_repository/stale_connection_locator.go, internal/controller/account_resolver.go, internal/controller/connected_client_recorder.go, internal/platform/logger/logger.go
Modify the logger calls to add the org_id label (just like the account label is currently added)
https://issues.redhat.com/browse/RHCLOUD-17729
A step towards replacing EBS account_number with org_id
Added org_id in every log that contains the account ID
=> Add org_id to logs [RHCLOUD-17729]

internal/controller/api/api.spec.json
Fix mismatch between API spec and implementation.
According to the spec the /connection_status operation returns 201 status code normally. However, the implementation in message_receiver.go sets the status code to 200. I assume the latter is the desired behavior.
Change the API spec to match the actual behavior.
N/A
=> fix mismatch between API spec and implementation

cmd/cloud-connector/inventory_stale_timestamp_updater.go, cmd/test_client/main.go, internal/cloud_connector/message_handlers.go, internal/cloud_connector/message_handlers_test.go, internal/connection_repository/stale_connection_locator.go, internal/controller/connected_client_recorder.go, internal/controller/connected_client_recorder_test.go
Register the host with inventory if the `package-manager` dispatcher is present
Config-Manager needs to be notified when a rhc connection is made which has the `package-manager` dispatcher.  Inventory will send out an event over kafka when a host is registered.  Config-Manager is watching for these events.
Modified the inventory based connected client recorder to send the `add_host` message to inventory if the connection has the 'package-manager' dispatcher.
Added some automated tests to verify that the `add_host` message is sent to the kafka writer if the connection has the `package-manager` dispatcher.  These tests are still a work in progress that we can continue to improve as we go along, but its a start.
- …
=> Register the host with inventory if the 'package-manager' dispatcher is present

internal/connection_repository/permitted_tenant_connection_locator.go, internal/connection_repository/permitted_tenant_connection_locator_test.go
Modify permitted tenants selection logic to guard against null org_id matches
=> Modify permitted tenants selection logic to guard against null org_id matches

internal/controller/connected_client_recorder.go, internal/controller/connected_client_recorder_test.go
Start sending the OrgID to inventory when hosts are created / updated.
With the shift from EBS account-numbers to OrgID we should now be propagating the OrgID to all connected services alongside the Account number.
Added the "org_id" field to the host data being sent to the inventory topic.
It looks like there are already tests in place that look for the OrgID.
JIRA:  https://issues.redhat.com/browse/RHCLOUD-18530
=> RHCLOUD-18530: Send org-id to inventory

deploy/clowdapp.yml
Explicitly set the deployment strategy to recreate for the mqtt consumer
There can only be one mqtt consumer running at a time.  This was the default configuration for a time, now its not.  So I'm explicitly setting it.
=> Explicitly set the deployment strategy to recreate for the mqtt consumer

deploy/clowdapp.yml, deploy/run_org_id_populator.yaml
Add an openshift job that will run the org-id column population utility.
Its possible that some of the rows in the connections table might not have an org-id.  The org-id needs to be populated moving forward.  Newly established connections will have the org-id already populated.  Its possible that "old" connections will not have the org-id column populated.
This PR adds an openshift job to run the org-id column population utility.  The utility will be pulled in as an image when the job is kicked off.
Manual testing and verification using gabi
=> Add org id populator job

deploy/clowdapp.yml, deploy/run_org_id_populator.yaml
Explicitly set the cloudwatch batch frequency on the org-id column population job
Make sure the logs are pushed to cloudwatch before the process exits.
=> Explicitly set the cloudwatch batch frequency on the org-id column population job

README.md, cmd/cloud-connector/api_server.go, internal/config/config.go, internal/connection_repository/sql_connection_locator_v2.go, internal/connection_repository/types.go, internal/controller/api/connection_mediator_v2.go, internal/controller/api/management.go, internal/controller/api/management_test.go, internal/controller/api/message_receiver.go, internal/controller/api/message_receiver_test.go, internal/controller/api/utils.go, internal/platform/logger/logger.go
Implement the v2 rest interface for the internal "customer" facing operations.
The v2 rest interface does not require explicitly passing the account number / org id as part of the request body.  The v2 endpoints do require org-id header (x-rh-cloud-connector-org-id) when using psk based authentication.
The internal "customer" facing v2 calls are: 
POST /v2/connections/{client_id}/message
GET /v2/connections/{client_id}/status
GET /v2/connections (return the list of connections that belong to an org)
Account number is no longer the primary tenant id within the platform.
- v2 connection lookup is separate from the http interface
- v2 connection lookup does not use the proxy factory anymore
- v2 connection lookup just returns the state of the connection
- proxy factory can take connection …
=> Implement the v2 rest interface

db/migrations/000008_drop-permitted-tenenants-column.down.sql, db/migrations/000008_drop-permitted-tenenants-column.up.sql, internal/connection_repository/sql_connection_registrar.go, internal/connection_repository/sql_connection_registrar_test.go
Create a db migration that removes the `permitted_tenants` column from the `connections` table
https://issues.redhat.com/browse/RHCLOUD-20479
The `permitted_tenants` column is no longer being used
Adds an additional migration to remove the index and drop the field
Also updated the `sql_connection_registrar` to stop using the `permitted_tenants` field
Updated `sql_connection_registrar_test` to stop looking for `permitted_tenants`
Migration checked in ephemeral:
=> Add a migration to remove the permitted_tenants column [RHCLOUD-20479]

dashboards/grafana-dashboard-insights-cloud-connector-general.configmap.yaml
Update the Grafana Dashboard to include the following ([RHCLOUD-19364](https://issues.redhat.com/browse/RHCLOUD-19364)):
- number of MQTT messages consumed
- number of Kafka messages consumed
- number of inventory messages produced (success / failed)
- number of MQTT messages sent (success / failed)
These changes add additional observability of the Kafka and MQTT consumers.
Exported and updated the JSON of the existing Grafana dashboard
=> Update Grafana dashboard [RHCLOUD-19364]

internal/controller/api/connection_mediator_v2.go, internal/controller/api/connection_mediator_v2_test.go, internal/controller/api/message_receiver.go, internal/controller/api/message_receiver_test.go
The `payload` field for the post body of the v1 and v2 message endpoint is now optional.
[Jira ticket](https://issues.redhat.com/browse/RHCLOUD-20916)
playbook-dispatcher's cancel operation needs to pass a `directive` that does not have a `payload` associated with it
Removed the `validate:"required"` json tags for the Payload fields.
Tests added for both the v1 and v2 to demonstrate the behavior.
=> Making payload field optional for the v1 and v2 message endpoint [RHCLOUD-20916]

dashboards/grafana-dashboard-insights-cloud-connector-general.configmap.yaml
Trying to determine why the updated dashboard isn't getting promoted.  Bump the version and see if it gets deployed.   I dunno...
=> Bump the version in the grafana dashboard

deploy/template-prod.yml, deploy/template.yml, internal/config/config.go
----
Updating references from the old 3scale Dev and Stage deployments `apicast.3scale-(dev|stage).svc.cluster.local` to the new 3scale dev deployment `gateway.3scale-(dev|stage).svc.cluster.local`
The reason for this change is the Infrastructure Team has stood up a new 3scale (Gateway) Deployment to support service serving certificates. Currently, both the old and new deployments are running in parallel so we can aid workstreams in the change over.
=> Update ref to 3 scale dev deployment

internal/connection_repository/stale_connection_locator.go
Modify the stale timestamp updater to use org_id as the main tenant id
[RHCLOUD-22877]
We are not using the account number as the main tenant id any longer
Manual testing
=> Modify the stale timestamp updater to use org_id as the main tenant id

cmd/cloud-connector/inventory_stale_timestamp_updater.go, internal/connection_repository/stale_connection_locator.go
Do not assume callers of updatetimestamp construct logger correctly
=> Do not assume callers of updatetimestamp construct logger correctly

deploy/clowdapp.yml
Disables the minimum 3 replicas requirement for mqtt  consumer.
Using more than 1 replica for mqtt consumer will ingest the same mqtt message multiple times.
Added the `ignore-check.kube-linter.io/minimum-three-replicas` annotation for the mqtt-message-consumer pod.
=> Disable min 3 replicas rule for mqtt-message-consumer

pr_check.sh
Disable E2E tests from the PR CHECK job
E2E tests require VMs that we don't have available in ephemeral envs.
-
-
=> Exclude E2E tests from PR CHECK

README.md
Include an optional "version" field to the ConnectionStatus message object.
=> docs: add "version" field to connection-status

cmd/cloud-connector/mqtt_message_consumer.go, internal/config/config.go, internal/mqtt/message_handlers.go
Cloud-Connector already attempts to flush the logs on shutdown.  This change modifies the mqtt consumer to flush the logs and then sleep for a configurable amount of time.  Hopefully this will make it so that the last few log messages make it to cloudwatch.
The last few log messages are not making it to cloudwatch.
=> Modify the mqtt consumer so that it sleeps for a bit after flushing the logs

.github/workflows/security-workflow-template.yml, Dockerfile
Added security scan to github action based on [Platform Security GitHub Workflow
](https://github.com/RedHatInsights/platform-security-gh-workflow#platform-security-github-workflow) repo.
Modified the registry url based on the troubleshooting recommendation here: https://github.com/RedHatInsights/platform-security-gh-workflow#troubleshooting
Jira [RHCLOUD-27007](https://issues.redhat.com/browse/RHCLOUD-27007)
Add new script into the github workflow folder
Provide a way to scan the container in a convenient, automated, and reliable manner within their GitHub repository.
=> Add PlatSec scan workflow

deploy/clowdapp.yml, internal/config/config.go
Changing the Invalid Handshake Reconnect Delay 
[RHCLOUD-28633]
This means that if a sends an online message but cloud-connector cannot map the client-id to an account/org-id then it cloud-connector will tell the client to reconnect in 60s
change the time from 5 seconds to 60 
- [x ] General Coding Practices
=> Invalid Handshake Reconnect Delay to 60 seconds

deploy/clowdapp.yml
Make consumer shutdown sleep time configurable.  Adjusting the config in app-interface to make the delay 25 seconds.
RHCLOUD-28525
=> Make consumer shutdown sleep time configurable

internal/controller/account_resolver.go
I added the debug logging as another way to confirm that caching was working as expected since we really don't have way to test this outside of stage.  It seems to working as expected so I'm changing the log level to trace
=> Only log in the account mapper cache when running at the trace log level

cmd/test_client/main.go, internal/cloud_connector/message_handlers.go, internal/cloud_connector/message_handlers_test.go, internal/cloud_connector/utils.go, internal/cloud_connector/utils_test.go
Sanitize the insights-id that is passed as a canonical fact.  If its invalid, remove it from the canonical facts (do not write it to the database, do not pass it to inventory)
=> Sanitize the insights-id that is passed as a canonical fact

internal/cloud_connector/message_handlers.go, internal/cloud_connector/message_handlers_test.go, internal/connection_repository/sql_connection_locator_v2.go, internal/connection_repository/sql_connection_locator_v2_test.go, internal/connection_repository/sql_connection_registrar.go, internal/connection_repository/sql_connection_registrar_test.go
[ ] Test this manually
- make sure a tenant-less connection can be updated on the next message received
- make sure tenant-less connections cannot be located by api 
- make sure tanant-less connections can be unregistered correctly
[ ] Modify "relaxed" connection locator to verify that the org_id is not empty (add a test here)
[ ] Add a test that verifies that a valid tenant can update a tenant-less connection
[ ] Add a test that verifies that a tenant-less connection can update a valid tenant connection
Any other notes about the PR that …
=> Do not send reconnect message on org id lookup failures

internal/cloud_connector/message_handlers.go
https://issues.redhat.com/browse/RHCLOUD-30651
Dispatcher entries can be pulled directly from debug log messages for alternative parsing and application.
The dispatcher map is marshalled to JSON and printed.
Tested with `TestProcessDispatchers()`. Example output:
```go
=== RUN   TestProcessDispatchers
time="2024-10-31T12:26:30-04:00" level=debug msg="Dispatchers found: {\"catalog\":{\"ApplicationType\":\"ima_app_type\",\"SourceRef\":\"ima_source_ref\",\"SrcName\":\"ima_source_name\",\"SrcType\":\"ima_source_type\"}}" func=github.com/RedHatInsights/cloud-connector/internal/cloud_connector.processDispatchers file="/home/jrodri/develop/cloud-connector/internal/cloud_connector/message_handlers.go:224" account=12345 client_id=98765 org_id=54321
--- PASS: TestProcessDispatchers (0.00s)
PASS
``` …
=> [RHCLOUD-30651] Independently log cloud-connector dispatchers map

dashboards/grafana-dashboard-insights-cloud-connector-general.configmap.yaml
https://issues.redhat.com/browse/RHCLOUD-37401
Replace old Kafka lag metrics in Grafana with those pulled from AWS MSK.
The old datasource is being deprecated.
- Update the "Kafka Messages Lag" panel from `kafka_consumergroup_group_lag` to `aws_kafka_sum_offset_lag_sum`
- Update the "Kafka Message Consumer Latency SLO" to reflect the intended SLO: 95% backlog of less than 10 messages, rolling 28-day window (Slack message)
Visualized while making the changes in Grafana.
> [!IMPORTANT]
>
> This metric only started reporting correctly for Cloud Connector a couple hours ago (Prometheus graph), so it will remain drafted until roughly 28 days have passed, to ensure the SLO metric reports accurately.
=> [RHCLOUD-37401] Replace Grafana consumergroup metrics with AWS MSK
